# Generated by Django 4.2.1 on 2023-07-20 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0031_alter_blogauthor_profilephoto_and_more"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="profiledp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiledp",
                to="navigation.mediabucket",
            ),
        ),
    ]
