# Generated by Django 4.2.1 on 2023-05-28 15:11

import autoslug.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, null=True, unique=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="title", unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text1", models.TextField(blank=True, null=True)),
                ("text2", models.TextField(blank=True, null=True)),
                ("text3", models.TextField(blank=True, null=True)),
                ("text4", models.TextField(blank=True, null=True)),
                ("text5", models.TextField(blank=True, null=True)),
                ("text6", models.TextField(blank=True, null=True)),
                ("text7", models.TextField(blank=True, null=True)),
                ("text8", models.TextField(blank=True, null=True)),
                ("text9", models.TextField(blank=True, null=True)),
                ("text10", models.TextField(blank=True, null=True)),
                ("text11", models.TextField(blank=True, null=True)),
                ("text12", models.TextField(blank=True, null=True)),
                ("text13", models.TextField(blank=True, null=True)),
                ("text14", models.TextField(blank=True, null=True)),
                ("text15", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MediaBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/")),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=200, null=True)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Ourwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, null=True, unique=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="title", unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(unique=True)),
                ("discription", models.TextField()),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="title", unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, null=True, unique=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="title", unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pricingdetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pricingtag", models.TextField(blank=True, null=True)),
                ("pricingheading", models.TextField(blank=True, null=True)),
                ("pricingsubheading", models.TextField(blank=True, null=True)),
                ("pricingparagraph", models.TextField(blank=True, null=True)),
                ("pricingsimpletext", models.TextField(blank=True, null=True)),
                ("pricingbtntext", models.TextField(blank=True, null=True)),
                ("pricingbtnurl", models.TextField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Pricingdetails",
                        to="navigation.pricing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sectiontwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text1", models.TextField(blank=True, null=True)),
                ("text2", models.TextField(blank=True, null=True)),
                ("text3", models.TextField(blank=True, null=True)),
                ("text4", models.TextField(blank=True, null=True)),
                ("text5", models.TextField(blank=True, null=True)),
                ("text6", models.TextField(blank=True, null=True)),
                ("text7", models.TextField(blank=True, null=True)),
                ("text8", models.TextField(blank=True, null=True)),
                ("text9", models.TextField(blank=True, null=True)),
                ("text10", models.TextField(blank=True, null=True)),
                ("text11", models.TextField(blank=True, null=True)),
                ("text12", models.TextField(blank=True, null=True)),
                ("text13", models.TextField(blank=True, null=True)),
                ("text14", models.TextField(blank=True, null=True)),
                ("text15", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="VideoBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="video/")),
            ],
        ),
        migrations.CreateModel(
            name="Whyus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, null=True, unique=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="title", unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Whyussectiontwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectiontwoheading", models.TextField(blank=True, null=True)),
                ("sectiontwosubheading", models.TextField(blank=True, null=True)),
                ("sectiontwodiscription", models.TextField(blank=True, null=True)),
                ("sectiontwobtntext", models.TextField(blank=True, null=True)),
                ("sectiontwobtnurl", models.TextField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Whyussectiontwo",
                        to="navigation.whyus",
                    ),
                ),
                (
                    "sectiontwoimage1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whyussectiontwoimage1",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectiontwoimage2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whyussectiontwoimage2",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Whyussectionthree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectiononeheading", models.TextField(blank=True, null=True)),
                ("sectiononesubheading", models.TextField(blank=True, null=True)),
                ("sectiononediscription", models.TextField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Whyussectionthree",
                        to="navigation.whyus",
                    ),
                ),
                (
                    "sectionthreevideo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whyussectionthreevideo",
                        to="navigation.videobucket",
                    ),
                ),
                (
                    "sectionthreevideoimg",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whyussectionthreevideoimg",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Whyussectionsix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectionsixdiscription", models.TextField(blank=True, null=True)),
                ("sectionsixheading", models.TextField(blank=True, null=True)),
                ("sectionsixsubheading", models.TextField(blank=True, null=True)),
                ("sectionsixparagraph", models.TextField(blank=True, null=True)),
                ("sectionsixpoint1", models.TextField(blank=True, null=True)),
                ("sectionsixpoint2", models.TextField(blank=True, null=True)),
                ("sectionsixbtntext", models.TextField(blank=True, null=True)),
                ("sectionsixbtnurl", models.TextField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Whyussectionsix",
                        to="navigation.whyus",
                    ),
                ),
                (
                    "sectionsiximage1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whyussectionsiximage1",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectionsiximage2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whyussectionsiximage2",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectionsiximage3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whyussectionsiximage3",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectionsiximage4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whyussectionsiximage4",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectionsiximage5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whyussectionsiximage5",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectionsiximage6",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whyussectionsiximage6",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Whyussectionseven",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectionsevenheading", models.TextField(blank=True, null=True)),
                ("sectionsevensubheading", models.TextField(blank=True, null=True)),
                ("sectionsevendiscription", models.TextField(blank=True, null=True)),
                ("sectionsevenbtnurl", models.TextField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whyussectionseven",
                        to="navigation.whyus",
                    ),
                ),
                (
                    "sectionsevenimg",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whyussectionsevenimg",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Whyussectionfour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectionfourtext1", models.TextField(blank=True, null=True)),
                ("sectionfournumber1", models.TextField(blank=True, null=True)),
                ("sectionfourdiscription1", models.TextField(blank=True, null=True)),
                ("sectionfourtext2", models.TextField(blank=True, null=True)),
                ("sectionfournumber2", models.TextField(blank=True, null=True)),
                ("sectionfourdiscription2", models.TextField(blank=True, null=True)),
                ("sectionfourtext3", models.TextField(blank=True, null=True)),
                ("sectionfournumber3", models.TextField(blank=True, null=True)),
                ("sectionfourdiscription3", models.TextField(blank=True, null=True)),
                ("sectionfournumber4", models.TextField(blank=True, null=True)),
                ("sectionfourdiscription4", models.TextField(blank=True, null=True)),
                ("sectionfourtext", models.TextField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Whyussectionfour",
                        to="navigation.whyus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Whyussectionfive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectionfivediscription", models.TextField(blank=True, null=True)),
                ("sectionfiveheading", models.TextField(blank=True, null=True)),
                ("sectionfivesubheading", models.TextField(blank=True, null=True)),
                ("sectionfiveparagraph", models.TextField(blank=True, null=True)),
                ("sectionfivepoint1", models.TextField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Whyussectionfive",
                        to="navigation.whyus",
                    ),
                ),
                (
                    "sectionfiveimage1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whyussectionfiveimage1",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectionfiveimage2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whyussectionfiveimage2",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectionfiveimage3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whyussectionfiveimage3",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="whyusreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField()),
                ("userdesignation", models.TextField()),
                ("userreview", models.TextField()),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whyusreview",
                        to="navigation.whyus",
                    ),
                ),
                (
                    "userphoto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whyusreviewuserphoto",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=200)),
                (
                    "menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_menu",
                        to="navigation.menu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Slidersection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slidersection",
                        to="navigation.page",
                    ),
                ),
                (
                    "sliderimage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sliderimage",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Servicessectiontwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectiontwoheading", models.TextField(blank=True, null=True)),
                ("sectiontwosubheading", models.TextField(blank=True, null=True)),
                ("sectiontwodiscription", models.TextField(blank=True, null=True)),
                ("sectiontwobtntext", models.TextField(blank=True, null=True)),
                ("sectiontwobtnurl", models.TextField(blank=True, null=True)),
                ("sectiontwosimpletext", models.TextField(blank=True, null=True)),
                ("sectiontwoheading1", models.TextField(blank=True, null=True)),
                ("sectiontwoheadin2", models.TextField(blank=True, null=True)),
                ("sectiontwosubheading2", models.TextField(blank=True, null=True)),
                ("sectiontwourl1", models.TextField(blank=True, null=True)),
                ("sectiontwourl2", models.TextField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectiontwoservices",
                        to="navigation.page",
                    ),
                ),
                (
                    "sectiontwocoverimage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectiontwocoverimage",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectiontwoimage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectiontwoimage",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectiontwovideo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectiontwovideo",
                        to="navigation.videobucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServicessectionThree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectionthreeheading", models.TextField(blank=True, null=True)),
                ("sectionthreesubheading", models.TextField(blank=True, null=True)),
                ("sectionthreetext1", models.TextField(blank=True, null=True)),
                ("sectionthreetext1number", models.TextField(blank=True, null=True)),
                (
                    "sectionthreetext1discription",
                    models.TextField(blank=True, null=True),
                ),
                ("sectionthreetext2", models.TextField(blank=True, null=True)),
                ("sectionthreetext2number", models.TextField(blank=True, null=True)),
                (
                    "sectionthreetext2discription",
                    models.TextField(blank=True, null=True),
                ),
                ("sectionthreetext3", models.TextField(blank=True, null=True)),
                ("sectionthreetext3number", models.TextField(blank=True, null=True)),
                (
                    "sectionthreetext3discription",
                    models.TextField(blank=True, null=True),
                ),
                ("sectionthreetext4", models.TextField(blank=True, null=True)),
                ("sectionthreetext4number", models.TextField(blank=True, null=True)),
                (
                    "sectionthreetext4discription",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectionthreeservices",
                        to="navigation.page",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Servicessectionsix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectionthreeheading", models.TextField(blank=True, null=True)),
                ("sectionthreesubheading", models.TextField(blank=True, null=True)),
                ("sectionsixparagraph", models.TextField(blank=True, null=True)),
                ("sectionsixbtntext", models.TextField(blank=True, null=True)),
                ("sectionsixbtnurl", models.TextField(blank=True, null=True)),
                ("sectionsixreviewheading", models.TextField(blank=True, null=True)),
                ("sectionsixquestiontext", models.TextField(blank=True, null=True)),
                (
                    "sectionsixquestiondescription",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "sectionsixquestiondescriptiontext",
                    models.TextField(blank=True, null=True),
                ),
                ("sectionsixbtn2text", models.TextField(blank=True, null=True)),
                ("sectionsixbtn2texturl", models.TextField(blank=True, null=True)),
                ("sectionsixfaqheading", models.TextField(blank=True, null=True)),
                ("sectionsixfaqsubheading", models.TextField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectionsixservices",
                        to="navigation.page",
                    ),
                ),
                (
                    "sectionsiximage1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectionsiximage1",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectionsiximage2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectionsiximage2",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Servicessectionseven",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectionsevenheading", models.TextField(blank=True, null=True)),
                ("sectionsevensubheading", models.TextField(blank=True, null=True)),
                ("sectionsevenparagraph", models.TextField(blank=True, null=True)),
                ("sectionsevenpoint1", models.TextField(blank=True, null=True)),
                ("sectionsevenpoint2", models.TextField(blank=True, null=True)),
                ("sectionsevenpoint3", models.TextField(blank=True, null=True)),
                ("sectionsevenpoint4", models.TextField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectionsevenservices",
                        to="navigation.page",
                    ),
                ),
                (
                    "sectionsevenimage1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectionsevenimage1",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectionsevenimage2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectionsevenimage2",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectionsevenimage3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectionsevenimage3",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectionsevenimage4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectionsevenimage4",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectionsevenimage5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectionsevenimage5",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectionsevenimage6",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectionsevenimage6",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Servicessectionone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectiontoneheading", models.TextField(blank=True, null=True)),
                ("sectiontonesubheading", models.TextField(blank=True, null=True)),
                ("sectiontonediscription", models.TextField(blank=True, null=True)),
                ("sectiontonebtntext", models.TextField(blank=True, null=True)),
                ("sectiontonebtnurl", models.TextField(blank=True, null=True)),
                ("sectiontonesimpletext", models.TextField(blank=True, null=True)),
                ("sectiontoneheading1", models.TextField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectiononeservices",
                        to="navigation.page",
                    ),
                ),
                (
                    "sectiontoneimage1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectiontoneimage1",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectiontoneimage2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectiontoneimage2",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectiontoneimage3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectiontoneimage3",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Servicesreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField()),
                ("userdesignation", models.TextField()),
                ("userreview", models.TextField()),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicesreviewpage",
                        to="navigation.page",
                    ),
                ),
                (
                    "userphoto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicesuserphoto",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sectionthree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectionthreeheading", models.TextField(blank=True, null=True)),
                ("sectionthreesubheading", models.TextField(blank=True, null=True)),
                ("sectionthreediscription", models.TextField(blank=True, null=True)),
                ("sectionthreebtntext", models.TextField(blank=True, null=True)),
                (
                    "sectionthreevideodiscription",
                    models.TextField(blank=True, null=True),
                ),
                ("sectionthreeheading1", models.TextField(blank=True, null=True)),
                ("sectionthreesubheading1", models.TextField(blank=True, null=True)),
                ("sectionthreediscription1", models.TextField(blank=True, null=True)),
                ("sectionthreegetstartedbtn", models.TextField(blank=True, null=True)),
                ("sectionthreebtnurl", models.TextField(blank=True, null=True)),
                (
                    "sectionthreevideo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectionthreevideo",
                        to="navigation.videobucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sectionone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectiononeheading", models.TextField(blank=True, null=True)),
                ("sectiononesubheading", models.TextField(blank=True, null=True)),
                ("sectiononeemailinput", models.TextField(blank=True, null=True)),
                ("sectiononegetstartedbtn", models.TextField(blank=True, null=True)),
                ("sectiononebtnurl", models.TextField(blank=True, null=True)),
                ("sectiononedisplaytext", models.TextField(blank=True, null=True)),
                (
                    "sectiononeimage1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectiononeimage1",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectiononeimage2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectiononeimage2",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectiononeimage3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectiononeimage3",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectiononeimage4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectiononeimage4",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectiononeimage5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectiononeimage5",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sectionfour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectionfourtext1", models.TextField(blank=True, null=True)),
                ("Sectionfourtext2", models.TextField(blank=True, null=True)),
                ("Sectionfourtext3", models.TextField(blank=True, null=True)),
                ("Sectionfourtext4", models.TextField(blank=True, null=True)),
                ("sectionfourtext5", models.TextField(blank=True, null=True)),
                ("sectionfourtext6", models.TextField(blank=True, null=True)),
                ("sectionfourtext7", models.TextField(blank=True, null=True)),
                ("sectionfourtext8", models.TextField(blank=True, null=True)),
                ("sectionfourtext9", models.TextField(blank=True, null=True)),
                ("sectionfourtext10", models.TextField(blank=True, null=True)),
                ("sectionfourtext11", models.TextField(blank=True, null=True)),
                ("sectionfourtext12", models.TextField(blank=True, null=True)),
                ("sectionfourtext13", models.TextField(blank=True, null=True)),
                ("sectionfourtext14", models.TextField(blank=True, null=True)),
                ("sectionfourtext15", models.TextField(blank=True, null=True)),
                (
                    "sectionfourimage1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectionfourimage1",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectionfourimage2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectionfourimage2",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectionfourimage3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectionfourimage3",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectionfourimage4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectionfourimage4",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectionfourimage5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectionfourimage5",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pricinguserreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField()),
                ("userdesignation", models.TextField()),
                ("userreview", models.TextField()),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Pricinguserreview",
                        to="navigation.pricing",
                    ),
                ),
                (
                    "userphoto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricinguserphoto",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pricingsubdetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pricingsubtag", models.BooleanField(default=True)),
                ("pricingheading", models.TextField()),
                (
                    "pricingpage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricingpage",
                        to="navigation.pricingdetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pricingsectiontwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectiontwoheading", models.TextField(blank=True, null=True)),
                ("sectiontwopoint1", models.TextField(blank=True, null=True)),
                ("sectiontwopoint2", models.TextField(blank=True, null=True)),
                ("sectiontwopoint3", models.TextField(blank=True, null=True)),
                ("sectiontwopoint4", models.TextField(blank=True, null=True)),
                ("sectiontwopoint5", models.TextField(blank=True, null=True)),
                ("sectiontwopoint6", models.TextField(blank=True, null=True)),
                ("sectiontwocompareprice", models.TextField(blank=True, null=True)),
                ("sectiontwourl", models.TextField(blank=True, null=True)),
                ("sectiontwocapability", models.TextField(blank=True, null=True)),
                (
                    "pricepdf",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Pricingsectiontwo",
                        to="navigation.pricing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pricingsectionthree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectionthreeheading", models.TextField(blank=True, null=True)),
                ("sectionthreesubheading", models.TextField(blank=True, null=True)),
                ("sectionthreediscription", models.TextField(blank=True, null=True)),
                ("sectionthreetext", models.TextField(blank=True, null=True)),
                ("sectionthreesubheading2", models.TextField(blank=True, null=True)),
                ("sectionthreeparagraph", models.TextField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Pricingsectionthree",
                        to="navigation.pricing",
                    ),
                ),
                (
                    "sectionthreevideo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Pricingsectionthreevideo",
                        to="navigation.videobucket",
                    ),
                ),
                (
                    "sectionthreevideoimg",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectionthreevideoimg",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pricingsectionone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectiononeheading", models.TextField(blank=True, null=True)),
                ("sectiononesubheading", models.TextField(blank=True, null=True)),
                ("sectiononediscription", models.TextField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Pricingsectionone",
                        to="navigation.pricing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pricingsectionfour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectionfourheading", models.TextField(blank=True, null=True)),
                ("sectionfoursubheading", models.TextField(blank=True, null=True)),
                ("sectionfourparagraph", models.TextField(blank=True, null=True)),
                ("sectionfourpoint1", models.TextField(blank=True, null=True)),
                ("sectionfourpoint2", models.TextField(blank=True, null=True)),
                ("sectionfourpoint3", models.TextField(blank=True, null=True)),
                ("sectionfourpoint4", models.TextField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Pricingsectionfour",
                        to="navigation.pricing",
                    ),
                ),
                (
                    "sectionfourimage1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Pricingsectionfourimage1",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectionfourimage2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Pricingsectionfourimage2",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectionfourimage3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Pricingsectionfourimage3",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectionfourimage4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Pricingsectionfourimage4",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectionfourimage5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Pricingsectionfourimage5",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectionfourimage6",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Pricingsectionfourimage6",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PricingFaq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="PricingFaq",
                        to="navigation.pricing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ourworksectiontwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectiontwoheading", models.TextField(blank=True, null=True)),
                ("sectiontwosubheading", models.TextField(blank=True, null=True)),
                ("sectiontwodiscription", models.TextField(blank=True, null=True)),
                ("sectiontwotext", models.TextField(blank=True, null=True)),
                ("sectiontwobtntext", models.TextField(blank=True, null=True)),
                ("sectiontwobtnurl", models.TextField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ourworksectiontwo",
                        to="navigation.ourwork",
                    ),
                ),
                (
                    "sectiontwoimg",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ourworksectiontwoimg",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ourworksectionone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectiononeheading", models.TextField(blank=True, null=True)),
                ("sectiononesubheading", models.TextField(blank=True, null=True)),
                ("sectiononediscription", models.TextField(blank=True, null=True)),
                ("sectiononetext", models.TextField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ourworksectionone",
                        to="navigation.ourwork",
                    ),
                ),
                (
                    "sectiononeimg",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ourworksectiononeimg",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectiontwovideo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ourworksectiontwovideo",
                        to="navigation.videobucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HomepageReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField()),
                ("userdesignation", models.TextField()),
                ("userreview", models.TextField()),
                (
                    "userphoto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userphoto",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Header",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "headerlogo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logo",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="header",
                        to="navigation.menu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicesfaq",
                        to="navigation.page",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detailsheading", models.TextField(blank=True, null=True)),
                ("detailsdiscription", models.TextField(blank=True, null=True)),
                (
                    "detailsimage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detailsimage",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Blogsectiontwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectiontwoheading", models.TextField(blank=True, null=True)),
                ("sectiontwosubheading", models.TextField(blank=True, null=True)),
                ("sectiontwodiscription", models.TextField(blank=True, null=True)),
                ("sectiontwotext", models.TextField(blank=True, null=True)),
                ("sectiontwobtntext", models.TextField(blank=True, null=True)),
                ("sectiontwobtnurl", models.TextField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogsectiontwo",
                        to="navigation.blogs",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Blogsectionthree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectionthreeheading", models.TextField(blank=True, null=True)),
                ("sectionthreesubheading", models.TextField(blank=True, null=True)),
                ("sectionthreediscription", models.TextField(blank=True, null=True)),
                ("sectionthreetext", models.TextField(blank=True, null=True)),
                ("sectionthreebtntext", models.TextField(blank=True, null=True)),
                ("sectionthreebtnurl", models.TextField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Blogsectionthree",
                        to="navigation.blogs",
                    ),
                ),
                (
                    "sectionthreeimg",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogsectionthreeimg",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Blogsectionone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectiononeheading", models.TextField(blank=True, null=True)),
                ("sectiononesubheading", models.TextField(blank=True, null=True)),
                ("sectiononediscription", models.TextField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogsectionone",
                        to="navigation.blogs",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Blogsectionfour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectionfourheading", models.TextField(blank=True, null=True)),
                ("sectionfoursubheading", models.TextField(blank=True, null=True)),
                ("sectionfourdiscription", models.TextField(blank=True, null=True)),
                ("sectionfourtext", models.TextField(blank=True, null=True)),
                ("sectionfourbtnurl", models.TextField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Blogsectionfour",
                        to="navigation.blogs",
                    ),
                ),
                (
                    "sectionfourimg",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogsectionfourimg",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Position", models.TextField()),
                ("name", models.CharField(max_length=800)),
                ("title", models.CharField(max_length=800, unique=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="title", unique=True
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=800, null=True)),
                ("body", ckeditor_uploader.fields.RichTextUploadingField()),
                ("summary", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("tag", models.TextField()),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicesBlogPost",
                        to="navigation.page",
                    ),
                ),
                (
                    "profilephoto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profilephoto",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "thumbnail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogpostthumbnail",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
    ]
