# Generated by Django 4.2.1 on 2023-05-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "navigation",
            "0002_tag_remove_blogpost_position_remove_blogpost_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag",
            field=models.TextField(unique=True),
        ),
    ]
