# Generated by Django 4.2.1 on 2023-05-29 07:02

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0003_alter_tag_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Homepage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, null=True, unique=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="title", unique=True
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="details",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Homepagedetails",
                to="navigation.homepage",
            ),
        ),
        migrations.AddField(
            model_name="homepagereview",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Homepagereview",
                to="navigation.homepage",
            ),
        ),
        migrations.AddField(
            model_name="sectionfour",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Homepagesectionfour",
                to="navigation.homepage",
            ),
        ),
        migrations.AddField(
            model_name="sectionone",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Homepagesectionone",
                to="navigation.homepage",
            ),
        ),
        migrations.AddField(
            model_name="sectionthree",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Homepagesectionthree",
                to="navigation.homepage",
            ),
        ),
        migrations.AddField(
            model_name="sectiontwo",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Homepagesectiontwo",
                to="navigation.homepage",
            ),
        ),
    ]
