# Generated by Django 4.2.1 on 2023-05-31 05:18

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0006_page_pageimg"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookacall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, null=True, unique=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="title", unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookacallSlidersection2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="BookacallSlidersection2",
                        to="navigation.bookacall",
                    ),
                ),
                (
                    "sliderimage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookacallsliderimagesection2",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookacallSlidersection1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="BookacallSlidersection1",
                        to="navigation.bookacall",
                    ),
                ),
                (
                    "sliderimage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookacallsliderimagesection1",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bookacallsectiontwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectiontwotext1", models.TextField(blank=True, null=True)),
                ("sectiontwosubheading1", models.TextField(blank=True, null=True)),
                ("sectiontwodiscription1", models.TextField(blank=True, null=True)),
                ("sectiontwotext2", models.TextField(blank=True, null=True)),
                ("sectiontwosubheading2", models.TextField(blank=True, null=True)),
                ("sectiontwodiscription2", models.TextField(blank=True, null=True)),
                ("sectiontwotext3", models.TextField(blank=True, null=True)),
                ("sectiontwosubheading3", models.TextField(blank=True, null=True)),
                ("sectiontwodiscription3", models.TextField(blank=True, null=True)),
                ("sectiontwotext4", models.TextField(blank=True, null=True)),
                ("sectiontwosubheading4", models.TextField(blank=True, null=True)),
                ("sectiontwodiscription4", models.TextField(blank=True, null=True)),
                ("sectiontwocopyrighttext", models.TextField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Bookacallsectiontwo",
                        to="navigation.bookacall",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bookacallsectionone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectiononeheading", models.TextField(blank=True, null=True)),
                ("sectiononesubheading", models.TextField(blank=True, null=True)),
                ("sectiononediscription", models.TextField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Bookacallsectionone",
                        to="navigation.bookacall",
                    ),
                ),
                (
                    "sectiononeimg1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookacallsectiononeimg1",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectiononeimg2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookacallsectiononeimg2",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectiononeimg3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookacallsectiononeimg3",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
    ]
