# Generated by Django 4.2.1 on 2023-05-31 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0007_bookacall_bookacallslidersection2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomepageSlidersection2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="HomepageSlidersection2",
                        to="navigation.homepage",
                    ),
                ),
                (
                    "sliderimage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepagesliderimagesection2",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HomepageSlidersection1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="HomepageSlidersection1",
                        to="navigation.homepage",
                    ),
                ),
                (
                    "sliderimage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepagesliderimagesection1",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
    ]
