# Generated by Django 4.2.1 on 2023-06-01 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0008_homepageslidersection2_homepageslidersection1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blogposttag",
                to="navigation.tag",
            ),
        ),
    ]
