# Generated by Django 4.2.1 on 2023-06-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0009_alter_blogpost_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="tag",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="tag",
            field=models.ManyToManyField(related_name="blogposts", to="navigation.tag"),
        ),
    ]
