# Generated by Django 4.2.1 on 2023-06-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0010_remove_blogpost_tag_blogpost_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emailinput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("social", models.TextField(unique=True)),
                ("socialurl", models.TextField(unique=True)),
            ],
        ),
    ]
