# Generated by Django 4.2.1 on 2023-06-28 06:35

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0012_blogauthor_slug_tag_slug_alter_blogauthor_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="menu_isbtn",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="tag", unique=True
            ),
        ),
    ]
