# Generated by Django 4.2.1 on 2023-06-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0013_menu_menu_isbtn_alter_tag_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="footer",
            old_name="text1",
            new_name="Footerheading",
        ),
        migrations.RenameField(
            model_name="footer",
            old_name="text10",
            new_name="footercopyrighttext",
        ),
        migrations.RenameField(
            model_name="footer",
            old_name="text11",
            new_name="footerdiscrip",
        ),
        migrations.RenameField(
            model_name="footer",
            old_name="text12",
            new_name="footeremailpageholder",
        ),
        migrations.RenameField(
            model_name="footer",
            old_name="text13",
            new_name="footerprivacy",
        ),
        migrations.RenameField(
            model_name="footer",
            old_name="text2",
            new_name="footerprivacylink",
        ),
        migrations.RenameField(
            model_name="footer",
            old_name="text3",
            new_name="footersmalldis",
        ),
        migrations.RenameField(
            model_name="footer",
            old_name="text4",
            new_name="footersmalldisbold",
        ),
        migrations.RenameField(
            model_name="footer",
            old_name="text5",
            new_name="footerstatuspage",
        ),
        migrations.RenameField(
            model_name="footer",
            old_name="text6",
            new_name="footerstatuspagelink",
        ),
        migrations.RenameField(
            model_name="footer",
            old_name="text7",
            new_name="footersubscription",
        ),
        migrations.RenameField(
            model_name="footer",
            old_name="text8",
            new_name="footerterms",
        ),
        migrations.RenameField(
            model_name="footer",
            old_name="text9",
            new_name="footertermsofuselink",
        ),
    ]
