# Generated by Django 4.2.1 on 2023-06-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0016_commonreview_commonslidersection1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text4", models.TextField(blank=True, null=True)),
                ("text5", models.TextField(blank=True, null=True)),
                ("text6", models.TextField(blank=True, null=True)),
                ("text7", models.TextField(blank=True, null=True)),
                ("text8", models.TextField(blank=True, null=True)),
                ("text9", models.TextField(blank=True, null=True)),
                ("text10", models.TextField(blank=True, null=True)),
                ("text11", models.TextField(blank=True, null=True)),
                ("text12", models.TextField(blank=True, null=True)),
                ("text13", models.TextField(blank=True, null=True)),
                ("text14", models.TextField(blank=True, null=True)),
                ("text15", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="sectiontwo",
            name="text10",
        ),
        migrations.RemoveField(
            model_name="sectiontwo",
            name="text11",
        ),
        migrations.RemoveField(
            model_name="sectiontwo",
            name="text12",
        ),
        migrations.RemoveField(
            model_name="sectiontwo",
            name="text13",
        ),
        migrations.RemoveField(
            model_name="sectiontwo",
            name="text14",
        ),
        migrations.RemoveField(
            model_name="sectiontwo",
            name="text15",
        ),
        migrations.RemoveField(
            model_name="sectiontwo",
            name="text4",
        ),
        migrations.RemoveField(
            model_name="sectiontwo",
            name="text5",
        ),
        migrations.RemoveField(
            model_name="sectiontwo",
            name="text6",
        ),
        migrations.RemoveField(
            model_name="sectiontwo",
            name="text7",
        ),
        migrations.RemoveField(
            model_name="sectiontwo",
            name="text8",
        ),
        migrations.RemoveField(
            model_name="sectiontwo",
            name="text9",
        ),
    ]
