# Generated by Django 4.2.1 on 2023-07-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0017_facts_remove_sectiontwo_text10_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="facts",
            old_name="text10",
            new_name="desc1",
        ),
        migrations.RenameField(
            model_name="facts",
            old_name="text11",
            new_name="desc2",
        ),
        migrations.RenameField(
            model_name="facts",
            old_name="text12",
            new_name="desc3",
        ),
        migrations.RenameField(
            model_name="facts",
            old_name="text13",
            new_name="desc4",
        ),
        migrations.RenameField(
            model_name="facts",
            old_name="text14",
            new_name="subTitle1",
        ),
        migrations.RenameField(
            model_name="facts",
            old_name="text15",
            new_name="subTitle2",
        ),
        migrations.RenameField(
            model_name="facts",
            old_name="text4",
            new_name="subTitle3",
        ),
        migrations.RenameField(
            model_name="facts",
            old_name="text5",
            new_name="subTitle4",
        ),
        migrations.RenameField(
            model_name="facts",
            old_name="text6",
            new_name="title1",
        ),
        migrations.RenameField(
            model_name="facts",
            old_name="text7",
            new_name="title2",
        ),
        migrations.RenameField(
            model_name="facts",
            old_name="text8",
            new_name="title3",
        ),
        migrations.RenameField(
            model_name="facts",
            old_name="text9",
            new_name="title4",
        ),
    ]
