# Generated by Django 4.2.1 on 2023-07-02 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "navigation",
            "0018_rename_text10_facts_desc1_rename_text11_facts_desc2_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="whyussectionseven",
            old_name="sectionsevendiscription",
            new_name="sectionsevenbtntext",
        ),
        migrations.RenameField(
            model_name="whyussectionsix",
            old_name="sectionsixdiscription",
            new_name="sectionsiximage1details",
        ),
        migrations.RenameField(
            model_name="whyussectionsix",
            old_name="sectionsixparagraph",
            new_name="sectionsiximage2details",
        ),
        migrations.RenameField(
            model_name="whyussectionsix",
            old_name="sectionsixpoint1",
            new_name="sectionsiximage3details",
        ),
        migrations.RenameField(
            model_name="whyussectionsix",
            old_name="sectionsixpoint2",
            new_name="sectionsiximage4details",
        ),
        migrations.AddField(
            model_name="whyussectionseven",
            name="sectionsixmobileimg",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="whyussectionsevenimage2",
                to="navigation.mediabucket",
            ),
        ),
        migrations.AddField(
            model_name="whyussectionsix",
            name="sectionsiximage5details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whyussectionsix",
            name="sectionsiximage6details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
