# Generated by Django 4.2.1 on 2023-07-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "navigation",
            "0019_rename_sectionsevendiscription_whyussectionseven_sectionsevenbtntext_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="whyussectionfive",
            old_name="sectionfiveparagraph",
            new_name="sectionfivecolourtext",
        ),
        migrations.RenameField(
            model_name="whyussectionfive",
            old_name="sectionfivepoint1",
            new_name="sectionfiveimage1details",
        ),
        migrations.AddField(
            model_name="whyussectionfive",
            name="sectionfiveimage2details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whyussectionfive",
            name="sectionfiveimage3details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
