# Generated by Django 4.2.1 on 2023-07-02 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0022_remove_singlereview_page_delete_whyussectionfour"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whyussectionseven",
            name="sectionsixmobileimg",
        ),
        migrations.AddField(
            model_name="whyussectionseven",
            name="sectionsevenmobileimg",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="whyussectionsevenimagemobileimg",
                to="navigation.mediabucket",
            ),
        ),
        migrations.CreateModel(
            name="Pricingcta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Pricingctaheading", models.TextField(blank=True, null=True)),
                ("Pricingctasubheading", models.TextField(blank=True, null=True)),
                ("Pricingctabtntext", models.TextField(blank=True, null=True)),
                ("Pricingctabtnurl", models.TextField(blank=True, null=True)),
                (
                    "Pricingctaimg",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricingctaimg",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "Pricingctamobileimg",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricingctaimage2",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Pricingcta",
                        to="navigation.pricing",
                    ),
                ),
            ],
        ),
    ]
