# Generated by Django 4.2.1 on 2023-07-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "navigation",
            "0024_rename_sectionsixbtn2text_servicessectionsix_sectionsixcolourtext_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Userdata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("lastname", models.TextField()),
                ("email", models.TextField()),
                ("comapanyname", models.TextField()),
                ("reasontocontact", models.TextField()),
                ("phonenumber", models.IntegerField()),
                ("page", models.TextField()),
            ],
        ),
    ]
