# Generated by Django 4.2.1 on 2023-07-08 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0028_blogsectionfive"),
    ]

    operations = [
        migrations.CreateModel(
            name="Whyusmeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metakey", models.TextField()),
                ("metavalue", models.TextField()),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Whyusmeta",
                        to="navigation.whyus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Servicesmeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metakey", models.TextField()),
                ("metavalue", models.TextField()),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Servicesmeta",
                        to="navigation.page",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pricingmeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metakey", models.TextField()),
                ("metavalue", models.TextField()),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricingmeta",
                        to="navigation.pricing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ourworkmeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metakey", models.TextField()),
                ("metavalue", models.TextField()),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Ourworkmeta",
                        to="navigation.ourwork",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Homepagemeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metakey", models.TextField()),
                ("metavalue", models.TextField()),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Homepagemeta",
                        to="navigation.homepage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Blogsmeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metakey", models.TextField()),
                ("metavalue", models.TextField()),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Blogsmeta",
                        to="navigation.blogs",
                    ),
                ),
            ],
        ),
    ]
