# Generated by Django 4.2.1 on 2023-07-20 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0031_alter_blogauthor_profilephoto_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adminpanellogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tagline", models.TextField(blank=True, null=True)),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adminpanellogo",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
    ]
