# Generated by Django 4.2.1 on 2023-07-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0032_adminpanellogo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facts",
            name="desc1",
            field=models.TextField(blank=True, default="null", null=True),
        ),
        migrations.AlterField(
            model_name="facts",
            name="desc2",
            field=models.TextField(blank=True, default="null", null=True),
        ),
        migrations.AlterField(
            model_name="facts",
            name="desc3",
            field=models.TextField(blank=True, default="null", null=True),
        ),
        migrations.AlterField(
            model_name="facts",
            name="desc4",
            field=models.TextField(blank=True, default="null", null=True),
        ),
        migrations.AlterField(
            model_name="facts",
            name="subTitle1",
            field=models.TextField(blank=True, default="null", null=True),
        ),
        migrations.AlterField(
            model_name="facts",
            name="subTitle2",
            field=models.TextField(blank=True, default="null", null=True),
        ),
        migrations.AlterField(
            model_name="facts",
            name="subTitle3",
            field=models.TextField(blank=True, default="null", null=True),
        ),
        migrations.AlterField(
            model_name="facts",
            name="subTitle4",
            field=models.TextField(blank=True, default="null", null=True),
        ),
        migrations.AlterField(
            model_name="facts",
            name="title1",
            field=models.TextField(blank=True, default="null", null=True),
        ),
        migrations.AlterField(
            model_name="facts",
            name="title2",
            field=models.TextField(blank=True, default="null", null=True),
        ),
        migrations.AlterField(
            model_name="facts",
            name="title3",
            field=models.TextField(blank=True, default="null", null=True),
        ),
        migrations.AlterField(
            model_name="facts",
            name="title4",
            field=models.TextField(blank=True, default="null", null=True),
        ),
    ]
