# Generated by Django 4.2.1 on 2023-07-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0033_alter_facts_desc1_alter_facts_desc2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediabucket",
            name="image",
            field=models.FileField(upload_to="media/"),
        ),
    ]
