# Generated by Django 4.2.1 on 2023-07-22 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0035_category_subcategory_blogpost_subcategory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="page",
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="servicesBlogPost",
                to="navigation.category",
            ),
        ),
    ]
