# Generated by Django 4.2.1 on 2023-07-23 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0038_alter_blogpost_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Featuredpost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("featuredposttext", models.TextField(blank=True, null=True)),
                (
                    "allblogimg",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allblogimg",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "blogs",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blogcollection",
                        to="navigation.blogpost",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="FeaturedpostBlogsectionfive",
                        to="navigation.blogs",
                    ),
                ),
            ],
        ),
    ]
