# Generated by Django 4.2.1 on 2023-07-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0039_featuredpost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="featuredpost",
            name="blogs",
        ),
        migrations.AddField(
            model_name="featuredpost",
            name="blogs",
            field=models.ManyToManyField(
                blank=True, related_name="featured_posts", to="navigation.blogpost"
            ),
        ),
    ]
