# Generated by Django 4.2.1 on 2023-07-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0040_remove_featuredpost_blogs_featuredpost_blogs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commonbranding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commonbrandingtext", models.TextField(blank=True, null=True)),
                (
                    "image1",
                    models.ManyToManyField(
                        blank=True, related_name="slider1", to="navigation.mediabucket"
                    ),
                ),
                (
                    "image2",
                    models.ManyToManyField(
                        blank=True, related_name="slider2", to="navigation.mediabucket"
                    ),
                ),
            ],
        ),
    ]
