# Generated by Django 4.2.1 on 2023-07-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0042_servicesblog"),
    ]

    operations = [
        migrations.AddField(
            model_name="singlereview",
            name="brandingtext",
            field=models.TextField(blank=True, null=True),
        ),
    ]
