# Generated by Django 4.2.1 on 2023-07-25 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0043_singlereview_brandingtext"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuredpost",
            name="thumbimage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="thumbimage",
                to="navigation.mediabucket",
            ),
        ),
    ]
