# Generated by Django 4.2.1 on 2023-07-27 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0044_featuredpost_thumbimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="header",
            name="appdiscription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="header",
            name="appname",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="header",
            name="favicon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="favicon",
                to="navigation.mediabucket",
            ),
        ),
        migrations.AddField(
            model_name="header",
            name="headerblacknwhitelogo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headerblacknwhitelogo",
                to="navigation.mediabucket",
            ),
        ),
    ]
