# Generated by Django 4.2.1 on 2023-08-01 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "navigation",
            "0045_header_appdiscription_header_appname_header_favicon_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mediabucket",
            options={"ordering": ["-id"]},
        ),
    ]
