# Generated by Django 4.2.1 on 2023-08-01 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0047_alter_videobucket_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogauthor",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="blogsmeta",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="commonslidersection1",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="commonslidersection2",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="details",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="homepagemeta",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="menu",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="ourworkmeta",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="page",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="pricingmeta",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="servicesmeta",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="submenu",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="whyusmeta",
            options={"ordering": ["-id"]},
        ),
    ]
