# Generated by Django 4.2.1 on 2023-09-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0049_pricingsectionone_sectiononebannerimg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="whyussectionthree",
            name="sectiononegetstartedlink",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whyussectionthree",
            name="sectiononegetstartedtext",
            field=models.TextField(blank=True, null=True),
        ),
    ]
