# Generated by Django 4.2.1 on 2023-09-01 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0050_whyussectionthree_sectiononegetstartedlink_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ourworksectionfive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectionfivetopheading", models.TextField(blank=True, null=True)),
                ("sectionfivesubheading", models.TextField(blank=True, null=True)),
                ("sectionfivediscription", models.TextField(blank=True, null=True)),
                ("sectionfiveheading", models.TextField(blank=True, null=True)),
                ("sectionfivetopsubheading", models.TextField(blank=True, null=True)),
                ("sectionfivecolourtext", models.TextField(blank=True, null=True)),
                ("sectionfiveimage1details", models.TextField(blank=True, null=True)),
                ("sectionfiveimage2details", models.TextField(blank=True, null=True)),
                ("sectionfiveimage3details", models.TextField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Ourworksectionfive",
                        to="navigation.ourwork",
                    ),
                ),
                (
                    "sectionfiveimage1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Ourworksectionfiveimage1",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectionfiveimage2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Ourworksectionfiveimage2",
                        to="navigation.mediabucket",
                    ),
                ),
                (
                    "sectionfiveimage3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Ourworksectionfiveimage3",
                        to="navigation.mediabucket",
                    ),
                ),
            ],
        ),
    ]
