# Generated by Django 4.2.1 on 2023-09-03 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0051_ourworksectionfive"),
    ]

    operations = [
        migrations.AddField(
            model_name="ourworksectionfive",
            name="sectionfiveimage4",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Ourworksectionfiveimage4",
                to="navigation.mediabucket",
            ),
        ),
        migrations.AddField(
            model_name="ourworksectionfive",
            name="sectionfiveimage4details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
